### ISSUE TITLE
Clarify workflow of specifying and updating arguments

### ISSUE THREAD

**Issue by paul-buerkner** [hsbadr/bayesian#2]
As discussed some time ago, I have finally started looking into the details of the bayesian package. However, I still struggle a bit with the current logic and intended workflow.

For example, I am unsure how to set and update prior and family consistently. Apparently, I can set `prior` in `bayesian()` but not the `family` argument. When using `set_engine` I can specify both of these arguments. I assume this is intentional but I don't fully understand the logic of it.

What is more, how can I update arguments that are not "main arguments" (such as `prior`) but, apparently only "engine-specific arguments" (such as `family`)? Of course I could reset the engine via `set_engine` but that then removes all the engine-specific arguments. 

Some other things are confusing to me as well, but they are likely outside of the control of `bayesian`. For example, I apparently have to specify the formula either via `fit(formula = ...)` if the object is a `model_spec` from `parsnip` or via `add_model(formula = ...)` if the object comes from `workflows`. In particular, in this latter case, `fit(formula = ...)` would not work.

**Comment by hsbadr** [comment]
> As discussed some time ago, I have finally started looking into the details of the bayesian package.

Great!

> For example, I am unsure how to set and update prior and family consistently. Apparently, I can set `prior` in `bayesian()` but not the `family` argument. When using `set_engine` I can specify both of these arguments. I assume this is intentional but I don't fully understand the logic of it.

`bayesian()` takes common/unified arguments for all engines, which can be renamed to each specific engine via `parsnip::set_model_arg`. However, this doesn't matter right now since we only support a single engine (`"brms"`). All other arguments that you want to pass to a specific engine would go to `set_engine`. With the single supported engine right now, I pass all arguments to `set_engine` which accepts all `brms::brm` arguments plus `formula.override` (and other arguments of `brms::update.brmsfit` for advanced use).

So , the general use that would also accept a `recipe` and a complicated `brmsformula` is as follows:
```r
  library(tidyverse)
  library(tidymodels)
  
  library(bayesian)

  # brmsformula
  brmsfmla <- bayesian_formula(...)
  
  # linear formula of all variables (used for the data processing via `recipes` and `workflows`)
  # could be automatically generated from the `brmsformula` using something like:
  fmla <- brmsfmla %>%
    bayesian_terms(
      resp_rhs_all = FALSE
    ) %>%
      pluck("allvars")
  
  # data preprocessing (see https://recipes.tidymodels.org)
  bayesian_recipe <- <training dataset> %>%
    recipe() %>%
    update_role(..., new_role = "outcome") %>%
    update_role(..., new_role = "predictor") %>%
    step_*(...)
  
  # model specs
  bayesian_model <- bayesian() %>%
    set_engine(
      "brms",
      formula.override = brmsfmla,
      family = brmsfmla %>%
        pluck("family"),
      prior = get_prior(...),
      ... # any arguments for `brms::brm`
    )
  
  # modeling workflow
  bayesian_workflow <- workflow() %>%
    add_recipe(bayesian_recipe) %>%
    add_model(
      bayesian_model,
      formula = fmla
    )
    
  # fit workflow
  bayesian_workflow.fit <- bayesian_workflow %>%
    fit(
      data = <training dataset>
    )
    
    # model evaluation / tuning / cross validation (typical tidymodels pipeline)
    ....
```

> What is more, how can I update arguments that are not "main arguments" (such as `prior`) but, apparently only "engine-specific arguments" (such as `family`)? Of course I could reset the engine via `set_engine` but that then removes all the engine-specific arguments.

You can update the model specs via `update.bayesian`, which also checks the arguments (we need to add more checks):
https://github.com/hsbadr/bayesian/blob/00756bb6616c07dd2b61becac8be6741004061df/R/bayesian.R#L272-L361

> Some other things are confusing to me as well, but they are likely outside of the control of `bayesian`. For example, I apparently have to specify the formula either via `fit(formula = ...)` if the object is a `model_spec` from `parsnip` or via `add_model(formula = ...)` if the object comes from `workflows`. In particular, in this latter case, `fit(formula = ...)` would not work.

I think the schematic above should address this question. Let me know if it's still confusing. `formula.override` can utilize any `brmsformula` while overriding the linear formula that's only used in the data processing.

I've found that the cross validation is much more efficient with `bayesian` compared to `projpred`, but that needs a few functions to create a simple user interface. I'll work on this at some point.

**Comment by paul-buerkner** [comment]
Thanks: That explains most of my questions. Still, I don't see how to update `family`. For example,

```R
bayesian() %>%
  set_engine("brms", family = poisson()) %>%
  update(family = negbinomial())
```

results in an error. Also, I am a little confused about `formula.overwrite`. Is this already documented somehwere?

**Comment by hsbadr** [comment]
> Thanks: That explains most of my questions. Still, I don't see how to update `family`. 

I see. The current implementation of `update.bayesian` doesn't accept `family` argument. I'll look into it.

> Also, I am a little confused about `formula.overwrite`. Is this already documented somehwere?

Yes, briefly in `bayesian_fit` params:
https://github.com/hsbadr/bayesian/blob/00756bb6616c07dd2b61becac8be6741004061df/R/bayesian.R#L383-L384

I introduced it because `tidymodels` ecosystem doesn't support nonlinear formulae. It allows fitting the model with any `brmsformula` while keeping it compatible with `tidymodels` modules (e.g. `recipes` for data processing, `rsampe` for resampling, `tune`/`yardstick` for model tuning/evaluation, `workflows`, ... etc.).

I  agree that `bayesian` needs a lot of work for documentation and tests. It works very well for my applications, though.

**Comment by hsbadr** [comment]
@paul-buerkner Do you really need the response variable in both sides of `allvars` in a `brmsformula` object?

**Comment by hsbadr** [comment]
> Thanks: That explains most of my questions. Still, I don't see how to update `family`. For example,
> 
> ```r
> bayesian() %>%
>   set_engine("brms", family = poisson()) %>%
>   update(family = negbinomial())
> ```
> 
> results in an error.

The following should work now:
```r
bayesian(
  family = poisson()
) %>%
  set_engine("brms") %>%
  update(
    family = negbinomial()
  )
```
Note that it's updated in the main arguments, not the engine-specific arguments.

**Comment by hsbadr** [comment]
@paul-buerkner I've added support to tune/update almost all `brms::brm` arguments (except the deprecated ones) in the model specification via `bayesian()` (main arguments). We can still specify engine-specific or other `Stan` arguments via `set_engine()`, as usual. Let me know if any of this doesn't make sense to you.

This will be a bit challenging when we decide to add more engines, but that can be handled by renaming or ignoring arguments per engine then (with using `parsnip::set_model_arg`).

**Comment by hsbadr** [comment]
Here's a very simple workflow (recipe + model specs) example:
```r
# data preprocessing (see https://recipes.tidymodels.org)
bayesian_recipe <- inhaler %>%
  recipe() %>%
  update_role(rating, new_role = "outcome") %>%
  update_role(treat, period, carry, subject, new_role = "predictor")

# model specs
bayesian_model <- bayesian() %>%
  set_engine("brms")

# modeling workflow
bayesian_workflow <- workflow() %>%
  add_recipe(bayesian_recipe) %>%
  add_model(
    bayesian_model,
    formula = rating ~ treat + period + carry + (1 | subject)
  )

# fit workflow
bayesian_workflow.fit <- bayesian_workflow %>%
  fit(data = inhaler)
```

The recipe may include steps for data processing, and you may set `brms::brm` arguments in the model specs via `bayesian()`. Note that `formula.override` is not required for this example.

**Comment by paul-buerkner** [comment]
Thank you!

- I wasn't necessarily suggesting to make all arguments "main arguments". I don't have a good feeling yet, which should be better "main" or "engine-specific". Instead, I think we should have a clear logic to differentiate the two if we ever want to support other engines. But, again, I don't really know how such a logic should look like.
- My main concern was that I didn't know how to properly `update` engine-specific arguments. With now everything being main arguments, of course this problem is solved for now at least.
- By default, the response variable is stored on the RHS in "raw form" so that we still retain the original variable even if our formula would look like `log(y) ~ x`. See, for example

```R
dat <- data.frame(y = rexp(10), x = rnorm(10))
model.frame(log(y) ~ x, dat)
```

- That said, you can control this behavior via `brmsterms(resp_rhs_all = FALSE)` which we might want to use in bayesian.

**Comment by hsbadr** [comment]
Agreed. we can explicitly set and update the engine-specific arguments. We don't use `parsnip::set_model_arg` yet since I didn't plan to add other engines. In general, I prefer to have the common and tunable options as main arguments and move all other arguments to the engines. We can refine the current design, if needed. The question for you is: do you think that any of `brms::brm` arguments should be excluded from the main model specification? and why, if any?

> you can control this behavior via `brmsterms(resp_rhs_all = FALSE)`

Great! Thank you.

**Comment by paul-buerkner** [comment]
I will have to think about the argument question for a bit.

**Comment by hsbadr** [comment]
> I will have to think about the argument question for a bit.

Take your time! It isn't urgent until we add more engines and unify their arguments.
